# Generated by Django 2.0.3 on 2018-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extract', '0004_listing_is_viewed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='site_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
